<a href="https://colab.research.google.com/github/M-I-N1985/python_para_analise_de_dados_wes_mckinney/blob/main/capitulo_6_wes_mckinney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lendo e escrevendo dados em formato-texto**
####read_csv, read_table, read_fwf, read_clipboard, read_excel, read_hdf, read_html, read_json, read_msgpack, read_pickle, read_sas, read_sql, read_stata, read_feather

##**Os argumentos opcionais dessas funções podem se enquadrar em algumas categorias:**

####Indexação,Inferência de tipos e conversão de dados, Parsing de data e hora, Iteração, Problemas com dados sujos,

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
pd.options.display.max_colwidth = 75
pd.options.display.max_columns = 20
np.set_printoptions(precision=4, suppress=True)

In [2]:
df0 = pd.read_csv('examples/ex1.csv')
df0

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [3]:
df1 = pd.read_table('examples/ex1.csv', sep = ',')
df1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [4]:
df2 = pd.read_csv('examples/ex2.csv', header=None)
df2

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [5]:
df3 = pd.read_table('examples/ex2.csv', sep=',', names = ['a', 'b', 'c', 'd', 'message'])
df3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
names = ['a', 'b', 'c', 'd', 'message']
df4 = pd.read_csv('examples/ex2.csv', names=names, index_col='message')
df4

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [7]:
parsed0 = pd.read_csv('examples/csv_mindex.csv')
parsed0

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [8]:
parsed1 = pd.read_csv('examples/csv_mindex.csv', index_col=['key1', 'key2'])
parsed1

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [9]:
list(open('examples/ex3.txt'))  # casos em que a tabela não tem um delimitador físico

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [10]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [11]:
pd.read_csv('examples/ex4.csv')

                                                                       # hey!
a                                                   b        c   d    message
# just wanted to make things more difficult for you NaN      NaN NaN      NaN
# who reads CSV files with computers                 anyway? NaN NaN      NaN
1                                                   2        3   4      hello
5                                                   6        7   8      world
9                                                   10       11  12       foo

In [12]:
pd.read_csv('examples/ex4.csv', skiprows=[0,2,3])  # ignora as linhas

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [13]:
result = pd.read_csv('examples/ex5.csv', index_col="something")
result

           a   b     c   d message
something
one        1   2   3.0   4     NaN
two        5   6   NaN   8   world
three      9  10  11.0  12     foo

In [14]:
pd.read_csv('examples/ex5.csv', na_values=['NULL'])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [15]:
pd.isnull(result)

               a      b      c      d  message
something
one        False  False  False  False     True
two        False  False   True  False    False
three      False  False  False  False    False

In [16]:
pd.read_csv('examples/ex5.csv', na_values=['NULL'])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [17]:
pd.options.display.max_rows = 20

In [18]:
colunas = ['Argumentos', 'Descrição']
tabela2 = pd.read_excel('examples/tabela2.xlsx', index_col="Argumentos", names = colunas)
tabela2

                                                                                   Descrição
Argumentos
sep ou delimiter  Sequência de caracteres ou uma expressão regular a ser usada para separ...
header            Número da linha a ser usada como nomes de coluna; o default é 0 (primei...
index_col         Números ou nomes de coluna a serem usados como índice das linhas no res...
names             Lista de nomes de colunas para o resultado; pode ser combinado com head...
skiprows          Número de linhas a serem ignoradas no início do arquivo ou lista de núm...
na_values                                  Sequência de valores a serem substituídos por NA.
comment                            Caractere(s) para separar comentários no final das linhas
parse_dates       Tenta fazer parse de dados para datetime; o default é False. Se for Tru...
keep_date_col     Se as colunas forem reunidas para parse de data, mantém as colunas unid...
converters        Dicionário contendo o número ou o nome de colunas mapeados para funções...
dayfirst          Ao fazer parsing de datas potencialmente ambíguas, trata-as como estand...
date_parser                                          Função a ser usada para parse de datas.
nrows                                   Número de linhas a serem lidas no início do arquivo.
iterator                         Devolve um objeto TextParser para ler o arquivo aos poucos.
chunksize                                  Para iteração, é o tamanho das partes do arquivo.
skip_footer                          Número de linhas a serem ignoradas no final do arquivo.
verbose           Exibe várias informações de saída do parser, como o número de valores a...
encoding          Codificação de texto para Unicode (por exemplo, 'utf-8' para texto codi...
squeeze           Se os dados sujeitos a parsing contiverem apenas uma coluna, devolve um...
thousands                                     Separador de milhar (por exemplo, ',' ou '.').

In [19]:
sentinelas = {'message': ['foo', 'NA'], 'something':['two']}
pd.read_csv('examples/ex5.csv', na_values=sentinelas)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

###**Lendo arquivos-texto em partes**

In [20]:
pd.options.display.max_rows = 10  # Perceba que teremos tabelas com as 5 primeiras e 5 ultimas linhas

In [21]:
result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [22]:
result = pd.read_csv('examples/ex6.csv', nrows=5)
result

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [23]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)  # TextParser é um objeto iterator, pelo que entendi
tot=pd.Series([])
for piece in chunker:
  tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:10]

<ipython-input-23-ccaee1cd6485>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  tot=pd.Series([])

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

###**Escrevendo dados em formato texto**

In [24]:
dados = pd.read_csv('examples/ex5.csv')
dados

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [25]:
dados.to_csv('examples/out.csv')

In [26]:
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [27]:
import sys

In [28]:
dados.to_csv(sys.stdout, sep="|")  # mudando os separadores

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [29]:
dados.to_csv(sys.stdout, na_rep='NULL')  # trocando valores nulos

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [30]:
dados.to_csv(sys.stdout, index=False, header=False)  # desativando indices e colunas

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [31]:
dados.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])  # escrevendo um subconjunto das colunas na ordem de que eu quiser

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [32]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples/tseries.csv')
!cat examples/tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

In [33]:
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int64

###**Trabalhando com formatos delimitados**

In [34]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [35]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)
reader

In [36]:
for line in reader:
  print(line)
f.close

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [37]:
with open('examples/ex7.csv') as f:
  lines = list(csv.reader(f))
  print(lines)
  header, values = lines[0], lines[1:]

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [38]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [39]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = " "
    quoting = csv.QUOTE_MINIMAL

In [40]:
with open('examples/ex7.csv') as f:
    reader = csv.reader(f, dialect=my_dialect)

In [41]:
with open('examples/ex7.csv') as f:
  reader = csv.reader(f, delimiter='|')
  print(list(reader))

[['a,"b","c"'], ['1,"2","3"'], ['1,"2","3"']]

In [42]:
colunas = ['Argumento', 'Descrição']
tabela3 = pd.read_excel('examples/tabela3.xlsx', index_col='Argumento', names = colunas)
tabela3

                                                                                   Descrição
Argumento
lineterminator    Finalizador de linha para escrita; o default é '\r\n'. O reader ignora ...
quotechar         Caractere de aspas para campos com caracteres especiais (como um delimi...
quoting           Convenção para aspas. As opções incluem csv.QUOTE_ALL (aspas em todos o...
skipinitialspace     Ignora espaços em branco depois de cada delimitador; o default é False.
doublequote       Como lidar com o caractere de aspas em um campo; se for True,  é duplo ...
escapechar        String para escapar o delimitador se quoting estiver definido com csv.Q...

In [43]:
with open('mydata.csv', 'w', encoding='utf-8') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

In [44]:
!cat mydata.csv

one;two;three
1;2;3
4;5;6
7;8;9

###**Dados JSON**

In [45]:
obj = """
{"nome": "Iuri",
 "cidades_vividas": ["Porto Alegre", "Florianópolis", "New York", "San Francisco"],
 "pet": null,
 "primos": [{"nome": "Guilherme", "idade": 34, "hobbies": ["surf", "futebol"]},
              {"nome": "Daniel", "idade": 33, "hobbies": ["pesca", "corrida"]}]
}
"""

In [46]:
import json

resultado = json.loads(obj)
resultado

{'nome': 'Iuri',
 'cidades_vividas': ['Porto Alegre',
  'Florianópolis',
  'New York',
  'San Francisco'],
 'pet': None,
 'primos': [{'nome': 'Guilherme', 'idade': 34, 'hobbies': ['surf', 'futebol']},
  {'nome': 'Daniel', 'idade': 33, 'hobbies': ['pesca', 'corrida']}]}

In [47]:
asjson = json.dumps(resultado)

In [48]:
primos = pd.DataFrame(resultado['primos'], columns=['nome', 'idade'])
primos

        nome  idade
0  Guilherme     34
1     Daniel     33

In [49]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [50]:
dados = pd.read_json('examples/example.json')  # As opções default para pandas.read_json supõem que cada objeto no array JSON seja uma linha da tabela:
dados

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [51]:
print(dados.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [52]:
print(dados.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

###**XML e HTML: web scraping**

In [53]:
%pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (4.9.2)

In [54]:
%pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (4.6.3)

In [55]:
%pip install html5lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: html5lib in /usr/local/lib/python3.8/dist-packages (1.0.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib) (1.15.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib) (0.5.1)

In [56]:
tabelas = pd.read_html('examples/fdic_failed_bank_list.html')
tabelas

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [57]:
len(tabelas)

1

In [58]:
falencias = tabelas[0]
falencias.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [59]:
falencias_ano = pd.to_datetime(falencias['Closing Date'])
falencias_ano

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [60]:
falencias_ano.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

###**Fazendo parse de XML com lxml.objectify**

In [61]:
from lxml import objectify

In [62]:
path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [63]:
dados = []
pular_campos = ['PARENT_SEQ', 'INDICATOR_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES']

In [64]:
for elt in root.INDICATOR:
  el_data = {}
  for child in elt.getchildren():
    if child.tag in pular_campos:
      continue
    el_data[child.tag] = child.pyval
  dados.append(el_data)

In [65]:
perf = pd.DataFrame(dados)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [66]:
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

In [67]:
root

In [68]:
root.get('href')

'http://www.google.com'

In [69]:
root.text

'Google'

###**6.2 Formatos de dados binários**

In [70]:
frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [71]:
frame.to_pickle('examples/frame_pickle')

In [72]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

###**Usando o formato HDF5**

In [73]:
frame = pd.DataFrame({'a':np.random.randn(100)})

In [74]:
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [75]:
store['obj1']

           a
0  -0.204708
1   0.478943
2  -0.519439
3  -0.555730
4   1.965781
..       ...
95  0.795253
96  0.118110
97 -0.748532
98  0.584970
99  0.152677

[100 rows x 1 columns]

In [76]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  1.007189
11 -1.296221
12  0.274992
13  0.228913
14  1.352917
15  0.886429

In [77]:
#store.close()

In [78]:
frame.to_hdf('mydata.h5', 'obj3', format='table')

In [79]:
#pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

###**Lendo arquivos do Microsoft Excel**

In [80]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')  # Se você estiver lendo várias planilhas de um arquivo, será mais rápido criar o ExcelFile

In [81]:
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [82]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [83]:
writer = pd.ExcelWriter('examples/ex2.xlsx')

In [84]:
frame.to_excel(writer, 'Sheet1')
writer.save()

In [85]:
frame.to_excel('examples/ex2.xlsx')

In [86]:
pd.read_excel('examples/ex2.xlsx')

   Unnamed: 0  Unnamed: 0.1  a   b   c   d message
0           0             0  1   2   3   4   hello
1           1             1  5   6   7   8   world
2           2             2  9  10  11  12     foo

In [87]:
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

###**Interagindo com APIs web**

In [88]:
import requests

In [89]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [90]:
resp = requests.get(url)
resp

In [91]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51842',
  'id': 1615455662,
  'node_id': 'PR_kwDOAA0YD85LlLoZ',
  'number': 51842,
  'title': 'Update series.py',
  'user': {'login': 'ggold7046',
   'id': 98327736,
   'node_id': 'U_kgDOBdxcuA',
   'avatar_url': 'https://avatars.githubusercontent.com/u/98327736?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/ggold7046',
   'html_url': 'https://github.com/ggold7046',
   'followers_url': 'https://api.github.com/users/ggold7046/followers',
   'following_url': 'https://api.github.com/users/ggold7046/following{/other_user}',
   'gists_url': 'https://api.github.com/users/ggold7046/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/ggold7046/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/ggold7046/subscriptions',
   'organizations_url': 'https://api.github.com/users/ggold7046/orgs',
   'repos_url': 'https://api.github.com/users/ggold7046/repos',
   'events_url': 'https://api.github.com/users/ggold7046/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/ggold7046/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-03-08T15:22:04Z',
  'updated_at': '2023-03-08T15:22:04Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51842',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51842',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51842.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51842.patch',
   'merged_at': None},
  'body': 'Added the example section.\r\n\r\n- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51841',
  'id': 1615266700,
  'node_id': 'PR_kwDOAA0YD85Lki8W',
  'number': 51841,
  'title': 'Backport PR #51741 on branch 2.0.x (BUG: indexing empty pyarrow backed object returning corrupt object)',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-03-08T13:23:12Z',
  'updated_at': '2023-03-08T13:23:12Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51841',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51841',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51841.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51841.patch',
   'merged_at': None},
  'body': '#51741\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51841/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51840',
  'id': 1615262330,
  'node_id': 'PR_kwDOAA0YD85LkiBl',
  'number': 51840,
  'title': 'Backport PR #51766 on branch 2.0.x (CLN: Use type_mapper instead of manual conversion)',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-03-08T13:19:51Z',
  'updated_at': '2023-03-08T13:19:51Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51840',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51840',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51840.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51840.patch',
   'merged_at': None},
  'body': '#51766',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51840/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/51839',
  'id': 1615205025,
  'node_id': 'I_kwDOAA0YD85gRhKh',
  'number': 51839,
  'title': 'DOC: Improve to_csv mode documentation',
  'user': {'login': 'MrPowers',
   'id': 2722395,
   'node_id': 'MDQ6VXNlcjI3MjIzOTU=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/2722395?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/MrPowers',
   'html_url': 'https://github.com/MrPowers',
   'followers_url': 'https://api.github.com/users/MrPowers/followers',
   'following_url': 'https://api.github.com/users/MrPowers/following{/other_user}',
   'gists_url': 'https://api.github.com/users/MrPowers/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/MrPowers/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/MrPowers/subscriptions',
   'organizations_url': 'https://api.github.com/users/MrPowers/orgs',
   'repos_url': 'https://api.github.com/users/MrPowers/repos',
   'events_url': 'https://api.github.com/users/MrPowers/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/MrPowers/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False,
    'description': None},
   {'id': 717120670,
    'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue',
    'name': 'good first issue',
    'color': '0e8a16',
    'default': True,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 3,
  'created_at': '2023-03-08T12:41:53Z',
  'updated_at': '2023-03-08T15:29:31Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "### Pandas version checks\n\n- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\n\n\n### Location of the documentation\n\nhttps://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html\n\n### Documentation problem\n\nThe `to_csv` mode method does not explicitly list the options for users.  It links to the Python `open()` method that contains some options that aren't relevant.\n\n### Suggested fix for documentation\n\nIt'd be nice to list the mode options right in the `to_csv` docs.  This should be significantly more user-friendly.  Suggested text:\r\n\r\n```\r\nmode: str, default ‘w’\r\n\r\nThe file write mode which can be `w`, `x`, or `a`.  `w` will write the file and overwrite another file if it already exists.  `x` will write the file, but error out if a file with the same name already exists.  `a` will append to the existing file.\r\n\r\nThe available write modes are the same as [open()](https://docs.python.org/3/library/functions.html#open).\r\n```",
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51839/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51835',
  'id': 1614452515,
  'node_id': 'PR_kwDOAA0YD85Lh2P5',
  'number': 51835,
  'title': 'STYLE: enable ruff TCH on some file',
  'user': {'login': 'luke396',
   'id': 77875500,
   'node_id': 'MDQ6VXNlcjc3ODc1NTAw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/77875500?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/luke396',
   'html_url': 'https://github.com/luke396',
   'followers_url': 'https://api.github.com/users/luke396/followers',
   'following_url': 'https://api.github.com/users/luke396/following{/other_user}',
   'gists_url': 'https://api.github.com/users/luke396/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/luke396/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/luke396/subscriptions',
   'organizations_url': 'https://api.github.com/users/luke396/orgs',
   'repos_url': 'https://api.github.com/users/luke396/repos',
   'events_url': 'https://api.github.com/users/luke396/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/luke396/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 2,
  'created_at': '2023-03-08T01:00:33Z',
  'updated_at': '2023-03-08T14:41:26Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51835',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51835',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51835.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51835.patch',
   'merged_at': None},
  'body': 'xref #51740, to fix\r\n```\r\n"pandas/core/construction.py" = ["TCH"] \r\n"pandas/core/missing.py" = ["TCH"] \r\n"pandas/tseries/*" = ["TCH"] \r\n"pandas/tests/*" = ["TCH"] \r\n"pandas/plotting/*" = ["TCH"] \r\n```',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51835/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51834',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51834/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51834/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51834/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51834',
  'id': 1614429344,
  'node_id': 'PR_kwDOAA0YD85LhxVy',
  'number': 51834,
  'title': 'CoW: Set copy=False in internal usages of Series/DataFrame constructors',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 2085877452,
    'node_id': 'MDU6TGFiZWwyMDg1ODc3NDUy',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Copy%20/%20view%20semantics',
    'name': 'Copy / view semantics',
    'color': '70e5ca',
    'default': False,
    'description': ''}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/42',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/42',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/42/labels',
   'id': 1945020,
   'node_id': 'MDk6TWlsZXN0b25lMTk0NTAyMA==',
   'number': 42,
   'title': '2.0',
   'description': 'on-merge: backport to 2.0.x',
   'creator': {'login': 'jreback',
    'id': 953992,
    'node_id': 'MDQ6VXNlcjk1Mzk5Mg==',
    'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/jreback',
    'html_url': 'https://github.com/jreback',
    'followers_url': 'https://api.github.com/users/jreback/followers',
    'following_url': 'https://api.github.com/users/jreback/following{/other_user}',
    'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions',
    'organizations_url': 'https://api.github.com/users/jreback/orgs',
    'repos_url': 'https://api.github.com/users/jreback/repos',
    'events_url': 'https://api.github.com/users/jreback/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/jreback/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 37,
   'closed_issues': 1549,
   'state': 'open',
   'created_at': '2016-08-16T13:21:24Z',
   'updated_at': '2023-03-08T09:13:06Z',
   'due_on': '2023-03-06T08:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2023-03-08T00:31:21Z',
  'updated_at': '2023-03-08T00:31:21Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51834',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51834',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51834.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51834.patch',
   'merged_at': None},

In [92]:
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/51842',
 'id': 1615455662,
 'node_id': 'PR_kwDOAA0YD85LlLoZ',
 'number': 51842,
 'title': 'Update series.py',
 'user': {'login': 'ggold7046',
  'id': 98327736,
  'node_id': 'U_kgDOBdxcuA',
  'avatar_url': 'https://avatars.githubusercontent.com/u/98327736?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/ggold7046',
  'html_url': 'https://github.com/ggold7046',
  'followers_url': 'https://api.github.com/users/ggold7046/followers',
  'following_url': 'https://api.github.com/users/ggold7046/following{/other_user}',
  'gists_url': 'https://api.github.com/users/ggold7046/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/ggold7046/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/ggold7046/subscriptions',
  'organizations_url': 'https://api.github.com/users/ggold7046/orgs',
  'repos_url': 'https://api.github.com/users/ggold7046/repos',
  'events_url': 'https://api.github.com/users/ggold7046/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/ggold7046/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2023-03-08T15:22:04Z',
 'updated_at': '2023-03-08T15:22:04Z',
 'closed_at': None,
 'author_association': 'NONE',
 'active_lock_reason': None,
 'draft': False,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51842',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51842',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/51842.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/51842.patch',
  'merged_at': None},
 'body': 'Added the example section.\r\n\r\n- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51842/timeline',
 'performed_via_github_app': None,
 'state_reason': None}

In [93]:
data[0]['title']

'Update series.py'

In [94]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,51842,Update series.py,[],open
1,51841,Backport PR #51741 on branch 2.0.x (BUG: indexing empty pyarrow backed ...,[],open
2,51840,Backport PR #51766 on branch 2.0.x (CLN: Use type_mapper instead of man...,[],open
3,51839,DOC: Improve to_csv mode documentation,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api....",open
4,51835,STYLE: enable ruff TCH on some file,[],open
...,...,...,...,...
25,51809,REF: Add ExtensionArray.map,"[{'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https...",open
26,51808,BUG: eval() method does not support some symbols in column name,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
27,51803,CoW: Add reference tracking to index when created from series,"[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw', 'url': 'http...",open
28,51801,BUG: read_csv regression from version 1.3.5 to 1.5.3,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
29,51799,PDEP-9: Allow third-party projects to register pandas connectors with a...,"[{'id': 4253279386, 'node_id': 'LA_kwDOAA0YD879g-Sa', 'url': 'https://a...",open

## Interagindo com Banco de Dados

In [95]:
import sqlite3

In [96]:
query="""
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20), c REAL, d INTEGER
);"""

con = sqlite3.connect('mydata.sqlite')
con.execute(query)

In [97]:
con.commit()

In [98]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]

stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"

In [99]:
con.executemany(stmt, data)

In [100]:
con.commit()

In [101]:
cursor = con.execute('select * from test')

In [102]:
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [103]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

In [104]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [105]:
import sqlalchemy as sqla  # outra forma de fazer conexão com o mesmo banco de dados

In [106]:
db = sqla.create_engine('sqlite:///mydata.sqlite')

In [107]:
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5