<a href="https://colab.research.google.com/github/M-I-N1985/python_para_analise_de_dados_wes_mckinney/blob/main/capitulo_6_wes_mckinney.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Lendo e escrevendo dados em formato-texto**
####read_csv, read_table, read_fwf, read_clipboard, read_excel, read_hdf, read_html, read_json, read_msgpack, read_pickle, read_sas, read_sql, read_stata, read_feather

##**Os argumentos opcionais dessas funções podem se enquadrar em algumas categorias:**

####Indexação,Inferência de tipos e conversão de dados, Parsing de data e hora, Iteração, Problemas com dados sujos,

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
pd.options.display.max_colwidth = 75
pd.options.display.max_columns = 20
np.set_printoptions(precision=4, suppress=True)

In [211]:
df0 = pd.read_csv('examples/ex1.csv')
df0

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [212]:
df1 = pd.read_table('examples/ex1.csv', sep = ',')
df1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [213]:
df2 = pd.read_csv('examples/ex2.csv', header=None)
df2

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [214]:
df3 = pd.read_table('examples/ex2.csv', sep=',', names = ['a', 'b', 'c', 'd', 'message'])
df3

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [215]:
names = ['a', 'b', 'c', 'd', 'message']
df4 = pd.read_csv('examples/ex2.csv', names=names, index_col='message')
df4

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [216]:
parsed0 = pd.read_csv('examples/csv_mindex.csv')
parsed0

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [217]:
parsed1 = pd.read_csv('examples/csv_mindex.csv', index_col=['key1', 'key2'])
parsed1

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [218]:
list(open('examples/ex3.txt'))  # casos em que a tabela não tem um delimitador físico

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

In [219]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [220]:
pd.read_csv('examples/ex4.csv')

                                                                       # hey!
a                                                   b        c   d    message
# just wanted to make things more difficult for you NaN      NaN NaN      NaN
# who reads CSV files with computers                 anyway? NaN NaN      NaN
1                                                   2        3   4      hello
5                                                   6        7   8      world
9                                                   10       11  12       foo

In [221]:
pd.read_csv('examples/ex4.csv', skiprows=[0,2,3])  # ignora as linhas

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [222]:
result = pd.read_csv('examples/ex5.csv', index_col="something")
result

           a   b     c   d message
something
one        1   2   3.0   4     NaN
two        5   6   NaN   8   world
three      9  10  11.0  12     foo

In [223]:
pd.read_csv('examples/ex5.csv', na_values=['NULL'])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [224]:
pd.isnull(result)

               a      b      c      d  message
something
one        False  False  False  False     True
two        False  False   True  False    False
three      False  False  False  False    False

In [225]:
pd.read_csv('examples/ex5.csv', na_values=['NULL'])

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [226]:
pd.options.display.max_rows = 20

In [227]:
colunas = ['Argumentos', 'Descrição']
tabela2 = pd.read_excel('examples/tabela2.xlsx', index_col="Argumentos", names = colunas)
tabela2

                                                                                   Descrição
Argumentos
sep ou delimiter  Sequência de caracteres ou uma expressão regular a ser usada para separ...
header            Número da linha a ser usada como nomes de coluna; o default é 0 (primei...
index_col         Números ou nomes de coluna a serem usados como índice das linhas no res...
names             Lista de nomes de colunas para o resultado; pode ser combinado com head...
skiprows          Número de linhas a serem ignoradas no início do arquivo ou lista de núm...
na_values                                  Sequência de valores a serem substituídos por NA.
comment                            Caractere(s) para separar comentários no final das linhas
parse_dates       Tenta fazer parse de dados para datetime; o default é False. Se for Tru...
keep_date_col     Se as colunas forem reunidas para parse de data, mantém as colunas unid...
converters        Dicionário contendo o número ou o nome de colunas mapeados para funções...
dayfirst          Ao fazer parsing de datas potencialmente ambíguas, trata-as como estand...
date_parser                                          Função a ser usada para parse de datas.
nrows                                   Número de linhas a serem lidas no início do arquivo.
iterator                         Devolve um objeto TextParser para ler o arquivo aos poucos.
chunksize                                  Para iteração, é o tamanho das partes do arquivo.
skip_footer                          Número de linhas a serem ignoradas no final do arquivo.
verbose           Exibe várias informações de saída do parser, como o número de valores a...
encoding          Codificação de texto para Unicode (por exemplo, 'utf-8' para texto codi...
squeeze           Se os dados sujeitos a parsing contiverem apenas uma coluna, devolve um...
thousands                                     Separador de milhar (por exemplo, ',' ou '.').

In [228]:
sentinelas = {'message': ['foo', 'NA'], 'something':['two']}
pd.read_csv('examples/ex5.csv', na_values=sentinelas)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

###**Lendo arquivos-texto em partes**

In [229]:
pd.options.display.max_rows = 10  # Perceba que teremos tabelas com as 5 primeiras e 5 ultimas linhas

In [230]:
result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [231]:
result = pd.read_csv('examples/ex6.csv', nrows=5)
result

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [232]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)  # TextParser é um objeto iterator, pelo que entendi
tot=pd.Series([])
for piece in chunker:
  tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)
tot[:10]

<ipython-input-232-ccaee1cd6485>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  tot=pd.Series([])

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

###**Escrevendo dados em formato texto**

In [233]:
dados = pd.read_csv('examples/ex5.csv')
dados

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [234]:
dados.to_csv('examples/out.csv')

In [235]:
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

In [236]:
import sys

In [237]:
dados.to_csv(sys.stdout, sep="|")  # mudando os separadores

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [238]:
dados.to_csv(sys.stdout, na_rep='NULL')  # trocando valores nulos

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [239]:
dados.to_csv(sys.stdout, index=False, header=False)  # desativando indices e colunas

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [240]:
dados.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])  # escrevendo um subconjunto das colunas na ordem de que eu quiser

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [241]:
dates = pd.date_range('1/1/2000', periods=7)
ts = pd.Series(np.arange(7), index=dates)
ts.to_csv('examples/tseries.csv')
!cat examples/tseries.csv

,0
2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

In [242]:
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int64

###**Trabalhando com formatos delimitados**

In [243]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [244]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)
reader

In [245]:
for line in reader:
  print(line)
f.close

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [246]:
with open('examples/ex7.csv') as f:
  lines = list(csv.reader(f))
  print(lines)
  header, values = lines[0], lines[1:]

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [247]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [248]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = " "
    quoting = csv.QUOTE_MINIMAL

In [249]:
with open('examples/ex7.csv') as f:
    reader = csv.reader(f, dialect=my_dialect)

In [250]:
with open('examples/ex7.csv') as f:
  reader = csv.reader(f, delimiter='|')
  print(list(reader))

[['a,"b","c"'], ['1,"2","3"'], ['1,"2","3"']]

In [251]:
colunas = ['Argumento', 'Descrição']
tabela3 = pd.read_excel('examples/tabela3.xlsx', index_col='Argumento', names = colunas)
tabela3

                                                                                   Descrição
Argumento
lineterminator    Finalizador de linha para escrita; o default é '\r\n'. O reader ignora ...
quotechar         Caractere de aspas para campos com caracteres especiais (como um delimi...
quoting           Convenção para aspas. As opções incluem csv.QUOTE_ALL (aspas em todos o...
skipinitialspace     Ignora espaços em branco depois de cada delimitador; o default é False.
doublequote       Como lidar com o caractere de aspas em um campo; se for True,  é duplo ...
escapechar        String para escapar o delimitador se quoting estiver definido com csv.Q...

In [252]:
with open('mydata.csv', 'w', encoding='utf-8') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

In [253]:
!cat mydata.csv

one;two;three
1;2;3
4;5;6
7;8;9

###**Dados JSON**

In [254]:
obj = """
{"nome": "Iuri",
 "cidades_vividas": ["Porto Alegre", "Florianópolis", "New York", "San Francisco"],
 "pet": null,
 "primos": [{"nome": "Guilherme", "idade": 34, "hobbies": ["surf", "futebol"]},
              {"nome": "Daniel", "idade": 33, "hobbies": ["pesca", "corrida"]}]
}
"""

In [255]:
import json

resultado = json.loads(obj)
resultado

{'nome': 'Iuri',
 'cidades_vividas': ['Porto Alegre',
  'Florianópolis',
  'New York',
  'San Francisco'],
 'pet': None,
 'primos': [{'nome': 'Guilherme', 'idade': 34, 'hobbies': ['surf', 'futebol']},
  {'nome': 'Daniel', 'idade': 33, 'hobbies': ['pesca', 'corrida']}]}

In [256]:
asjson = json.dumps(resultado)

In [257]:
primos = pd.DataFrame(resultado['primos'], columns=['nome', 'idade'])
primos

        nome  idade
0  Guilherme     34
1     Daniel     33

In [258]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [259]:
dados = pd.read_json('examples/example.json')  # As opções default para pandas.read_json supõem que cada objeto no array JSON seja uma linha da tabela:
dados

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [260]:
print(dados.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [261]:
print(dados.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

###**XML e HTML: web scraping**

In [262]:
%pip install lxml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (4.9.2)

In [263]:
%pip install beautifulsoup4

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (4.6.3)

In [264]:
%pip install html5lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: html5lib in /usr/local/lib/python3.8/dist-packages (1.0.1)
Requirement already satisfied: webencodings in /usr/local/lib/python3.8/dist-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.8/dist-packages (from html5lib) (1.15.0)

In [265]:
tabelas = pd.read_html('examples/fdic_failed_bank_list.html')
tabelas

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [266]:
len(tabelas)

1

In [267]:
falencias = tabelas[0]
falencias.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [268]:
falencias_ano = pd.to_datetime(falencias['Closing Date'])
falencias_ano

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [269]:
falencias_ano.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
       ...
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, Length: 15, dtype: int64

###**Fazendo parse de XML com lxml.objectify**

In [270]:
from lxml import objectify

In [271]:
path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [272]:
dados = []
pular_campos = ['PARENT_SEQ', 'INDICATOR_SEQ', 'DESIRED_CHANGE', 'DECIMAL_PLACES']

In [273]:
for elt in root.INDICATOR:
  el_data = {}
  for child in elt.getchildren():
    if child.tag in pular_campos:
      continue
    el_data[child.tag] = child.pyval
  dados.append(el_data)

In [274]:
perf = pd.DataFrame(dados)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at their destinations within 5 m...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [275]:
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

In [276]:
root

In [277]:
root.get('href')

'http://www.google.com'

In [278]:
root.text

'Google'

###**6.2 Formatos de dados binários**

In [279]:
frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [280]:
frame.to_pickle('examples/frame_pickle')

In [281]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

###**Usando o formato HDF5**

In [282]:
frame = pd.DataFrame({'a':np.random.randn(100)})

In [283]:
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [284]:
store['obj1']

           a
0  -0.204708
1   0.478943
2  -0.519439
3  -0.555730
4   1.965781
..       ...
95  0.795253
96  0.118110
97 -0.748532
98  0.584970
99  0.152677

[100 rows x 1 columns]

In [285]:
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  1.007189
11 -1.296221
12  0.274992
13  0.228913
14  1.352917
15  0.886429

In [286]:
store.close()

In [288]:
frame.to_hdf('mydata.h5', 'obj3', format='table')

In [290]:
#pd.read_hdf('mydata.h5', 'obj3', where=['index < 5'])

###**Lendo arquivos do Microsoft Excel**

In [4]:
xlsx = pd.ExcelFile('examples/ex1.xlsx')

In [5]:
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [6]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1')
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [7]:
writer = pd.ExcelWriter('examples/ex2.xlsx')

In [8]:
frame.to_excel(writer, 'Sheet1')
writer.save()

In [11]:
frame.to_excel('examples/ex2.xlsx')

In [12]:
pd.read_excel('examples/ex2.xlsx')

   Unnamed: 0  Unnamed: 0.1  a   b   c   d message
0           0             0  1   2   3   4   hello
1           1             1  5   6   7   8   world
2           2             2  9  10  11  12     foo

###**Interagindo com APIs web**

In [13]:
import requests

In [14]:
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'

In [16]:
resp = requests.get(url)
resp

In [18]:
data = resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51831',
  'id': 1614338025,
  'node_id': 'PR_kwDOAA0YD85LhddW',
  'number': 51831,
  'title': 'New feature',
  'user': {'login': 'Kalaweksh',
   'id': 121249707,
   'node_id': 'U_kgDOBzofqw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/121249707?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Kalaweksh',
   'html_url': 'https://github.com/Kalaweksh',
   'followers_url': 'https://api.github.com/users/Kalaweksh/followers',
   'following_url': 'https://api.github.com/users/Kalaweksh/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Kalaweksh/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Kalaweksh/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Kalaweksh/subscriptions',
   'organizations_url': 'https://api.github.com/users/Kalaweksh/orgs',
   'repos_url': 'https://api.github.com/users/Kalaweksh/repos',
   'events_url': 'https://api.github.com/users/Kalaweksh/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Kalaweksh/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-03-07T22:56:04Z',
  'updated_at': '2023-03-07T23:34:29Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51831',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51831',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51831.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51831.patch',
   'merged_at': None},
  'body': '- [x] closes #51830 \r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/51830',
  'id': 1614333773,
  'node_id': 'I_kwDOAA0YD85gOMdN',
  'number': 51830,
  'title': 'ENH: Read first n_rows of Parquet File',
  'user': {'login': 'Kalaweksh',
   'id': 121249707,
   'node_id': 'U_kgDOBzofqw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/121249707?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/Kalaweksh',
   'html_url': 'https://github.com/Kalaweksh',
   'followers_url': 'https://api.github.com/users/Kalaweksh/followers',
   'following_url': 'https://api.github.com/users/Kalaweksh/following{/other_user}',
   'gists_url': 'https://api.github.com/users/Kalaweksh/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/Kalaweksh/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/Kalaweksh/subscriptions',
   'organizations_url': 'https://api.github.com/users/Kalaweksh/orgs',
   'repos_url': 'https://api.github.com/users/Kalaweksh/repos',
   'events_url': 'https://api.github.com/users/Kalaweksh/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/Kalaweksh/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2023-03-07T22:51:13Z',
  'updated_at': '2023-03-07T22:52:01Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "### Feature Type\n\n- [X] Adding new functionality to pandas\n\n- [ ] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nUsing PyArrow to read the first n rows of a file, as suggested in #24511 could help more conveniently read part of a large DataFrame that may otherwise not fit into memory. \n\n### Feature Description\n\nAdd a parameter, n_rows, to read_parquet. Will use the ParquetFile.iterbatches() generator in the PyArrow implementation and ParquetFile.head() in the fastparquet implementation (although this would be purely for convenience and not have any performance benefits).\n\n### Alternative Solutions\n\nYou could currently use PyArrow:\r\nfrom pyarrow.parquet import ParquetFile\r\nimport pyarrow as pa \r\n\r\npf = ParquetFile('file_name.pq') \r\nfirst_ten_rows = next(pf.iter_batches(batch_size = 10)) \r\ndf = pa.Table.from_batches([first_ten_rows]).to_pandas() \r\n\n\n### Additional Context\n\n_No response_",
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51830/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/51829',
  'id': 1614317121,
  'node_id': 'I_kwDOAA0YD85gOIZB',
  'number': 51829,
  'title': 'ENH: read_csv warn about suspicious extensions',
  'user': {'login': 'janosh',
   'id': 30958850,
   'node_id': 'MDQ6VXNlcjMwOTU4ODUw',
   'avatar_url': 'https://avatars.githubusercontent.com/u/30958850?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/janosh',
   'html_url': 'https://github.com/janosh',
   'followers_url': 'https://api.github.com/users/janosh/followers',
   'following_url': 'https://api.github.com/users/janosh/following{/other_user}',
   'gists_url': 'https://api.github.com/users/janosh/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/janosh/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/janosh/subscriptions',
   'organizations_url': 'https://api.github.com/users/janosh/orgs',
   'repos_url': 'https://api.github.com/users/janosh/repos',
   'events_url': 'https://api.github.com/users/janosh/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/janosh/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76812,
    'node_id': 'MDU6TGFiZWw3NjgxMg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement',
    'name': 'Enhancement',
    'color': '4E9A06',
    'default': False,
    'description': None},
   {'id': 47229171,
    'node_id': 'MDU6TGFiZWw0NzIyOTE3MQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20CSV',
    'name': 'IO CSV',
    'color': '5319e7',
    'default': False,
    'description': 'read_csv, to_csv'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 3,
  'created_at': '2023-03-07T22:34:40Z',
  'updated_at': '2023-03-07T22:43:14Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': "### Feature Type\n\n- [ ] Adding new functionality to pandas\n\n- [ ] Changing existing functionality in pandas\n\n- [ ] Removing existing functionality in pandas\n\n\n### Problem Description\n\nI often copy-paste code like\r\n\r\n```py\r\npd.read_csv('some/long/file/path/data.csv')\r\n```\r\n\r\nand then just change the file name to a file with a different extension, forgetting to also change `pd.read_csv`.\r\n\r\n```py\r\npd.read_csv('some/long/file/path/other-data.json')  # seems to be stuck in an infinite loop\r\n```\r\n\r\nCurrently `pd.read_csv` seems to run forever trying to read a JSON file without raising an error or ever returning.\r\n\r\n\n\n### Feature Description\n\n`pd.read_csv` could issue a warning on suspicious extensions:\r\n\r\n```py\r\npd.read_csv('some/long/file/path/other-data.json')\r\n> Warning: This looks like the wrong reader for `.json` extension\r\n```\n\n### Alternative Solutions\n\nCould also add a flag `warnings: 'raise' | 'warn' | 'error' = 'warn'` to control this behavior.\n\n### Additional Context\n\n_No response_",
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51829/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51828',
  'id': 1614296920,
  'node_id': 'PR_kwDOAA0YD85LhUk8',
  'number': 51828,
  'title': 'ERR: Raise ValueError when non-default index is given for orc format',
  'user': {'login': 'phofl',
   'id': 61934744,
   'node_id': 'MDQ6VXNlcjYxOTM0NzQ0',
   'avatar_url': 'https://avatars.githubusercontent.com/u/61934744?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/phofl',
   'html_url': 'https://github.com/phofl',
   'followers_url': 'https://api.github.com/users/phofl/followers',
   'following_url': 'https://api.github.com/users/phofl/following{/other_user}',
   'gists_url': 'https://api.github.com/users/phofl/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/phofl/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/phofl/subscriptions',
   'organizations_url': 'https://api.github.com/users/phofl/orgs',
   'repos_url': 'https://api.github.com/users/phofl/repos',
   'events_url': 'https://api.github.com/users/phofl/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/phofl/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 685114413,
    'node_id': 'MDU6TGFiZWw2ODUxMTQ0MTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Parquet',
    'name': 'IO Parquet',
    'color': '5319e7',
    'default': False,
    'description': 'parquet, feather'},
   {'id': 3303158446,
    'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow',
    'name': 'Arrow',
    'color': 'f9d0c4',
    'default': False,
    'description': 'pyarrow functionality'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 2,
  'created_at': '2023-03-07T22:19:15Z',
  'updated_at': '2023-03-07T23:53:42Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51828',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51828',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51828.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51828.patch',
   'merged_at': None},
  'body': "- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n\r\norc can't handle indexes right now (they are dropped), so we should raise like we did in feather",
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51828/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51827',
  'id': 1614246656,
  'node_id': 'PR_kwDOAA0YD85LhKGE',
  'number': 51827,
  'title': 'Enabled ruff TCH on some files',
  'user': {'login': 'ErdiTk',
   'id': 24619655,
   'node_id': 'MDQ6VXNlcjI0NjE5NjU1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/24619655?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/ErdiTk',
   'html_url': 'https://github.com/ErdiTk',
   'followers_url': 'https://api.github.com/users/ErdiTk/followers',
   'following_url': 'https://api.github.com/users/ErdiTk/following{/other_user}',
   'gists_url': 'https://api.github.com/users/ErdiTk/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/ErdiTk/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/ErdiTk/subscriptions',
   'organizations_url': 'https://api.github.com/users/ErdiTk/orgs',
   'repos_url': 'https://api.github.com/users/ErdiTk/repos',
   'events_url': 'https://api.github.com/users/ErdiTk/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/ErdiTk/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 106935113,
    'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style',
    'name': 'Code Style',
    'color': 'eb6420',
    'default': False,
    'description': 'Code style, linting, code_checks'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 2,
  'created_at': '2023-03-07T21:38:17Z',
  'updated_at': '2023-03-07T23:52:32Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51827',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/51827',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/51827.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/51827.patch',
   'merged_at': None},
  'body': '\r\nCloses #51740 for the following elements:\r\n- [ ] "pandas/core/apply.py": no change was required\r\n- [ ] "pandas/core/base.py": no change was required\r\n- [ ] "pandas/core/algorithms.py": no change was required\r\n- [ ] "pandas/core/ops/*"\r\n- [ ] "pandas/core/sorting.py"\r\n\r\nNo change was required means that the command:\r\n`pre-commit run ruff --all-files`\r\nhad zero errors after removing the relative line from the `pyproject.toml` file without any change (can be tried by doing so in the main branch).',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51827/timeline',
  'performed_via_github_app': None,
  'state_reason': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51826',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51826/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51826/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51826/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/51826',
  'id': 1614240021,
  'node_id': 'I_kwDOAA0YD85gN1kV',
  'number': 51826,
  'title': 'BUG:  unexpected value returned when `.reindex`ing on a `pd.Series` with a `pd.IntervalIndex` when using `np.nan` as an index value',
  'user': {'login': 'benlawson',
   'id': 7769994,
   'node_id': 'MDQ6VXNlcjc3Njk5OTQ=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7769994?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/benlawson',
   'html_url': 'https://github.com/benlawson',
   'followers_url': 'https://api.github.com/users/benlawson/followers',
   'following_url': 'https://api.github.com/users/benlawson/following{/other_user}',
   'gists_url': 'https://api.github.com/users/benlawson/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/benlawson/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/benlawson/subscriptions',
   'organizations_url': 'https://api.github.com/users/benlawson/orgs',
   'repos_url': 'https://api.github.com/users/benlawson/repos',
   'events_url': 'https://api.github.com/users/benlawson/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/benlawson/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',

In [20]:
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/51831',
 'id': 1614338025,
 'node_id': 'PR_kwDOAA0YD85LhddW',
 'number': 51831,
 'title': 'New feature',
 'user': {'login': 'Kalaweksh',
  'id': 121249707,
  'node_id': 'U_kgDOBzofqw',
  'avatar_url': 'https://avatars.githubusercontent.com/u/121249707?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/Kalaweksh',
  'html_url': 'https://github.com/Kalaweksh',
  'followers_url': 'https://api.github.com/users/Kalaweksh/followers',
  'following_url': 'https://api.github.com/users/Kalaweksh/following{/other_user}',
  'gists_url': 'https://api.github.com/users/Kalaweksh/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/Kalaweksh/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/Kalaweksh/subscriptions',
  'organizations_url': 'https://api.github.com/users/Kalaweksh/orgs',
  'repos_url': 'https://api.github.com/users/Kalaweksh/repos',
  'events_url': 'https://api.github.com/users/Kalaweksh/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/Kalaweksh/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2023-03-07T22:56:04Z',
 'updated_at': '2023-03-07T23:34:29Z',
 'closed_at': None,
 'author_association': 'NONE',
 'active_lock_reason': None,
 'draft': False,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/51831',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/51831',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/51831.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/51831.patch',
  'merged_at': None},
 'body': '- [x] closes #51830 \r\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\r\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\r\n',
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/51831/timeline',
 'performed_via_github_app': None,
 'state_reason': None}

In [22]:
data[0]['title']

'New feature'

In [23]:
issues = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
issues

,number,title,labels,state
0,51831,New feature,[],open
1,51830,ENH: Read first n_rows of Parquet File,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.g...",open
2,51829,ENH: read_csv warn about suspicious extensions,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.g...",open
3,51828,ERR: Raise ValueError when non-default index is given for orc format,"[{'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODUxMTQ0MTM=', 'url': 'https...",open
4,51827,Enabled ruff TCH on some files,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=', 'url': 'https...",open
5,51826,BUG: unexpected value returned when `.reindex`ing on a `pd.Series` wit...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
6,51825,DOC: sort has no effect on filters,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api....",open
7,51824,Fix to_excel not respecting None values in MultiIndex,[],open
8,51823,PERF/REF: make window/groupby imports lazy,[],open
9,51821,BUG: to_csv to Google Cloud Storage ignores mode='a',"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
10,51820,BUG: Timedelta does not accept ISO 8601 duration strings with 3 digit h...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
11,51818,BUG: Series name impacts groupby function,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
12,51817,DEPR: scalar index for length-1-list level groupby,[],open
13,51816,add concat function dtype test,[],open
14,51815,BUG: Index with duplicate labels raises ValueError in Dataframe.query,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
15,51814,STYLE: Add auto fix to ruff,[],open
16,51813,REF: define arithmetic methods non-dynamically,[],open
17,51811,DEPR: observed=False default in groupby,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api....",open
18,51809,REF: Add ExtensionArray.map,[],open
19,51808,BUG: eval() method does not support some symbols in column name,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
20,51803,CoW: Add reference tracking to index when created from series,"[{'id': 1218227310, 'node_id': 'MDU6TGFiZWwxMjE4MjI3MzEw', 'url': 'http...",open
21,51801,BUG: read_csv regression from version 1.3.5 to 1.5.3,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
22,51799,PDEP-9: Allow third-party projects to register pandas connectors with a...,"[{'id': 4253279386, 'node_id': 'LA_kwDOAA0YD879g-Sa', 'url': 'https://a...",open
23,51797,STYLE enable ruff PLW2901,"[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=', 'url': 'https...",open
24,51796,method `df.merge` is resetting the index,[],open
25,51795,BUG: `axvspan` breaks when using pandas `.plot()` wrapper,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
26,51794,"STYLE: Enable ruff TCH on ""pandas/_libs/*""","[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=', 'url': 'https...",open
27,51792,PERF: cache sortings in groupby.ops,"[{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api....",open
28,51791,BUG: read_csv giving bus error (sometimes segfault too),"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.g...",open
29,51789,DOC: extension array with arrow,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api....",open

## Interagindo com Banco de Dados